### ISSUE TITLE
Remaining VL and SL are not shown

### ISSUE THREAD

**Issue by bryanjulius** [rsalayo/OpeniT.Timesheet.Issues#1]
I tried to upload my timesheet from sharepoint, all daily information are included but remaining VL and SL are not shown.
![vlandsl](https://cloud.githubusercontent.com/assets/6357522/25884108/8677101a-3582-11e7-8121-ab1eea724a78.jpg)

**Comment by rsalayo** [comment]
Thanks Master. This is still in progress.
