### ISSUE TITLE
Link to ticket numbers under Build Patch:<TEAM> should be linked to PAP instead of Redmine.

### ISSUE THREAD

**Issue by rccoros** [rsalayo/OpeniT.Timesheet.Issues#13]
Last April 3, 2017 I have an entry about updating patch 1491. I used Build Patch:GUI as the subprocess and used 1491 in the Task column. 1491 has a link but it redirects to redmine ticket 1491 instead to Patch 1491.

**Comment by rccoros** [comment]
Last April 3, 2017 I have an entry about updating patch 1491. I used Build Patch:GUI as the subprocess and used 1491 in the Task column. 1491 has a link but it redirects to redmine ticket 1491 instead to Patch 1491.

**Comment by rsalayo** [comment]
Thanks Master. Do you have an idea how we can put intelligence on this? Right now, depending on the process you chose. It will put an href based on the process.

> **Delivery**: https://app.liquidplanner.com/space/75822/projects/show/
> **Development**: http://redmine/issues/
> **Support**: https://cerberus.openit.com/display.php?ticket=
> **QA**: https://patch.openit.com/patches/
> **Technical Presales and Analysis**: https://cerberus.openit.com/display.php?ticket=

**Comment by rccoros** [comment]
I suppose we can use of the 1st digit of the SPID under Development.
All 4-3x  are Build-Patch:Team so any tasks with SPID like that can have the http://patch.openit.com/ as base link.

**Comment by rsalayo** [comment]
I thought creating a patch is still tied to a redmine? Should it be a redmine ticket instead?
I'll think about it... ;-)

**Comment by agvendiola** [comment]
Maybe check what's newer with the two? The quick workaround this without too much effort is to let the user decide what link it will create, e.g. P1491 for patches, R7822 for redmine.  The fallback without the first letter will be the intelligence you'll create.

**Comment by rsalayo** [comment]
I've decided I will add this now with conjunction to #30. Will be available when this issue closes from a commit. Though I won't be liable for XSS...

**Comment by rsalayo** [comment]
See teaser on #30

**Comment by rsalayo** [comment]
@rccoros, just touching base to see if you're able to take advantage of this functionality (#30).

**Comment by rccoros** [comment]
Yes! Thank you very much @rsalayo ! :+1:
