### ISSUE TITLE
Suggestion: Time In and Time Out

### ISSUE THREAD

**Issue by vbitara** [rsalayo/OpeniT.Timesheet.Issues#14]
For us in Night shift, I think it would be best to add a Time In and Time Out button somewhere in the Timesheet page and compute the total night shift hours.

Night shift hours starts from: 10:00 PM until 6:00 AM

Example:
Time IN: 6:00 PM
Time OUT: 5:00 AM
Night shift hours: 8 hrs (10:00 PM-5:00 AM)

**Comment by rsalayo** [comment]
Is this ok?
![image](https://cloud.githubusercontent.com/assets/1053166/26615665/5345e290-458e-11e7-8ce4-ca38a2b07c24.png)
