### ISSUE TITLE
Feature Request: Search box for previous tasks or descriptions

### ISSUE THREAD

**Issue by rsalayo** [rsalayo/OpeniT.Timesheet.Issues#17]
A generic Input text box to search previous descriptions.
Select a match and start the timer.
All other input fields are based from previous inputs.

**Comment by agvendiola** [comment]
Thanks for considering this.  And sorry for pushing the features I have in my old timesheet, hehe.  This is one of the things I'm missing from it that could be very helpful.

**Comment by rsalayo** [comment]
Of course. I agree, I see the need for it my self.
Can you also suggest the place to put this?

I don't want to waste too much white space as much as possible, so I'm trying to use anything that has nothing on the existing layout.
This location ok?
![image](https://cloud.githubusercontent.com/assets/1053166/26526690/34655268-4348-11e7-8aee-b871b7f134f9.png)

**Comment by agvendiola** [comment]
Thank you! That's great!

**Comment by rsalayo** [comment]
Please try and let me know your thoughts.
