### ISSUE TITLE
Cannot Open Timesheet Page

### ISSUE THREAD

**Issue by mellows18** [rsalayo/OpeniT.Timesheet.Issues#21]
This is when I'm trying to open the Timesheet page, it will not show the timesheet's content. Upon checking it with developer's tool, there's some errors shown:

![timesheet](https://cloud.githubusercontent.com/assets/8245032/26385996/296c8b4e-4076-11e7-9f43-b5c21e3092de.PNG)

**Comment by rsalayo** [comment]
Please hit CTRL+F5.
This will clear the cache. Let me know if it did the trick...

**Comment by mellows18** [comment]
Ow! It is okay now sir! Thank you! ^_^
