### ISSUE TITLE
Feature Request: (Minor) Time Remaining and Hours needed per day

### ISSUE THREAD

**Issue by vbitara** [rsalayo/OpeniT.Timesheet.Issues#22]
An indicator to know how many hours left you need to work and how many hrs per day is needed.

Example:

May Total: 154.81 hours
Time Remaining: 37.19 hours (6.20/day)

![image](https://cloud.githubusercontent.com/assets/28781641/26391848/f31bbfe4-4096-11e7-9d34-d30847de5b1b.png)

**Comment by rsalayo** [comment]
Try hovering on Today’s progress bar and see if this helps.

**Comment by agvendiola** [comment]
> Try hovering on Today’s progress bar and see if this helps.

Please make it 'always' visible, please?

**Comment by rsalayo** [comment]
This is the best I can do for now...
![image](https://cloud.githubusercontent.com/assets/1053166/26519258/ed1d40a6-4283-11e7-9dbc-95bd473735a9.png)

**Comment by agvendiola** [comment]
Thanks!
