### ISSUE TITLE
BUG: Excess hours from previous year was not credited

### ISSUE THREAD

**Issue by noeltelosa** [rsalayo/OpeniT.Timesheet.Issues#28]
After importing the excel file the excess hours from the previous year was not credited.

![excess_hours](https://cloud.githubusercontent.com/assets/5878258/26559246/01ab882a-44e1-11e7-835d-f93e10b295c3.png)

**Comment by rsalayo** [comment]
Not all excess hours are already encoded. We're still waiting for users to login first before we encode their excess hours.
