### ISSUE TITLE
Feature Request: a way to make a link in the Description column

### ISSUE THREAD

**Issue by agvendiola** [rsalayo/OpeniT.Timesheet.Issues#30]
Links to Redmine, Support or Patch page.  Some of us collapse short task routines into one entry.  A quick workaround is to use the Task column but it'll make the list long for each 5-minute-task entry.  Another feature request from Glaiza :-)

**Comment by rsalayo** [comment]
Do you have an idea on mind on how are we going to do that without taking performance hit? We need some kind of syntax for this. (E.g. #TicketNumber or some specifics)
Using the following prefixes
hashtag = Automatically assign URI based on the processed used.
P = Use patch URI (P1234)
RM = Use Redmine (RM11111)
LP = Use LiquidPlanner (LP1234567890)
...so on

**Comment by rsalayo** [comment]
Teaser:
![image](https://cloud.githubusercontent.com/assets/1053166/26813811/8f41a448-4a46-11e7-815b-0ac5bdfd3d4f.png)
