### ISSUE TITLE
Enhancement: Move the location of the search box near the input boxes

### ISSUE THREAD

**Issue by agvendiola** [rsalayo/OpeniT.Timesheet.Issues#32]
UX improvement: I search the task, then start it.  I have to scroll down to see it running.  Then I have to scroll back up again to use the search bar.

Nahihiya na ako ang dami kong feature request haha!

**Comment by rsalayo** [comment]
I can only move it anywhere inside the header and footer (those are outside the client side app - AngularJS).
I don't want to do any _hacks_ at the moment as I want to use best practice as much as possible.
This is the best I can do without changing how the framework is supposed to be used.
![image](https://cloud.githubusercontent.com/assets/1053166/26664684/04c4040a-4659-11e7-833c-37f9333c5609.png)
With conjunction to #35, it will froze along with the rest of the data inputs.
Another option is to prevent the page from scrolling by making the table scroll in place.

**Comment by rsalayo** [comment]
Added a horizontal line to separate it from the rest of the data inputs.
![image](https://cloud.githubusercontent.com/assets/1053166/26749726/9b42499a-47d6-11e7-93bf-2a9408f6367c.png)
Let me know if this works for you or if I should leave it where it is right now.

**Comment by agvendiola** [comment]
Thanks!
