### ISSUE TITLE
Feature request: Lock entries for HR use

### ISSUE THREAD

**Issue by agvendiola** [rsalayo/OpeniT.Timesheet.Issues#33]
This was raised up today and I think the best workflow here is to allow the employee to lock their entries upon the end of the month.  So the suggest changes would be

1. Another tab beside Analytic (or somewhere intuitive) called  'Lock'
2. A page under 'Lock' tab that has 
2.1. Start date field
2.2. End date field
2.3. Button (to lock)

Each employee will still be able to edit their entries until a hard stop of 5 days (existing Employee guidelines).  From there, HR will 'lock' the entries themselves.  So it's either the employee to lock anytime OR HR on the 5th day of the month.

**Comment by rsalayo** [comment]
I'm planning to add a submit button in the statistics page beside each month which will lock the whole month.

**Comment by agvendiola** [comment]
That also works :+1: Much convenient hehe

**Comment by rsalayo** [comment]
Progress...
![image](https://user-images.githubusercontent.com/1053166/27164764-18e53524-5155-11e7-8cde-e59991f27e0a.png)
![image](https://user-images.githubusercontent.com/1053166/27164811-75e220a2-5155-11e7-81fd-bf79e3c667be.png)

Comments? @agvendiola @lisleta @rccoros

**Comment by agvendiola** [comment]
Yep! Makes sense.
