### ISSUE TITLE
The "delete" symbol doesn't really fit on pinned tasks

### ISSUE THREAD

**Issue by cyborgar** [rsalayo/OpeniT.Timesheet.Issues#40]
This is clearly "nitpicking" but why not.

To me it seem more natural to have the "unpin" option tied to the "pinned" icon. I.e. clicking on "pinned" unpins a task instead of using the trashcan symbol. At least I tried to unpin a task that way the first time.

**Comment by rsalayo** [comment]
I actually planned to use the **pinned** icon from the start. But as you may have guessed, it doesn't look uniformed with the rest without the **delete** button. 
![image](https://cloud.githubusercontent.com/assets/1053166/26749770/63f59f90-47d7-11e7-9a28-7403a6c22488.png)
Another way that I can think of is to hide all buttons and only shows up when user's hover.

**Comment by cyborgar** [comment]
Perhaps the "pin task" concept is wrong. And "create template" is more
appropriate.  You are actually duplicating and not really pinning existing
entry.

3. jun. 2017 04.39 skrev "Romeo Salayo" <notifications@github.com>:
