### ISSUE TITLE
Giving visual queue in "task edit area" when selecting a template or updating an entry

### ISSUE THREAD

**Issue by cyborgar** [rsalayo/OpeniT.Timesheet.Issues#44]
Again this is a very trivial issue but it might be nice to have a visual indication that the fields on the left has been updated after activating a template or issue.

Something like having setting the background color to grey and fading quickly to white to show that there are stuff updated "here". You could even use different colors for template activation and ticket edit.

**Comment by rsalayo** [comment]
I've started looking into this, I'm not really a big fan of animation as it doesn't behave the same on all browsers. How about having a visual color depending on the mode (Copy/Edit)?

Something like:
![image](https://user-images.githubusercontent.com/1053166/26861474-93bdb2b4-4b09-11e7-87c1-c15d50516bc4.png)

![image](https://user-images.githubusercontent.com/1053166/26861481-a4104604-4b09-11e7-8bb2-264c53cc428a.png)

@lisleta @rccoros @agvendiola

**Comment by rsalayo** [comment]
I guess, I can add a little bit of animation...

**Comment by cyborgar** [comment]
I think the colors use actually helps a lot. I agree that animation most often just slow down the gui.
