### ISSUE TITLE
Context menu on a row entry to add and/or start the task on the current day

### ISSUE THREAD

**Issue by agvendiola** [rsalayo/OpeniT.Timesheet.Issues#46]
this is the current flow using the mouse:
- go to yesterday's date 
- click copy
- click today
- click start timer icon
- click start button

proposed- scenario #1: saves 2 clicks and 2 mouse movements
- go to yesterday's date
- right click task
- click start task today

proposed-scenario #2: saves x clicks and helps to organize
- go to yesterday's date
- right click task
- add this task today
- right click another task
- add this task today
- ...

possible problems:
- the value of 'today' for night shifts.  low visibility and impact since it only affects few people
- performance problem.  are context menus performed on the server side? 
- browser compatibility

**Comment by rsalayo** [comment]
Maybe Dropdowns are enough for previous day and keep Start Timer for current day?
http://getbootstrap.com/components/#dropdowns

**Comment by agvendiola** [comment]
Sure.  I didn't think of that.
