### ISSUE TITLE
Forgotten Active Timer Pop up

### ISSUE THREAD

**Issue by watz** [rsalayo/OpeniT.Timesheet.Issues#59]
Hi,

I am logged and still in the office (I am still on a regular shift and not in the middle of the night or dawn) but the active timer just logged out and when I clicked the tab for timesheet it shows the image below then the timer is stopped, I had to restart the timer and I am not aware when did it stopped...

Also when I try to start it again, the pop ups re occur, which have captured here:
![image](https://user-images.githubusercontent.com/930133/29066989-972f8716-7c63-11e7-9623-9864cee5ffa6.png)

Then it again stopped:
![image](https://user-images.githubusercontent.com/930133/29067068-ddd42f96-7c63-11e7-83cb-32d868c5104a.png)

Here are the pop ups when I tried to restart, it's 6pm.
![image](https://user-images.githubusercontent.com/930133/29067176-3a68205a-7c64-11e7-8cca-7b20d2dc14c8.png)

**Comment by rsalayo** [comment]
Thanks Walter.

We’ll adjust the limit to 12 hours. For now start a new task.
It doesn’t like someone working for the same task for X number of hours. hehe

**Comment by rsalayo** [comment]
Increased limit to 12 hours
